---
title: "Lullably & goodnight"
output: html_notebook
---
## operators =, ->, <-
```{r}
x = 3
a <- function(x) {
  x <<- x + 1
}
```

```{r}
a <- c(2,3,4) # create a vector
a # [1] 2 3 4
a[1] <- "abc"
a # [1] "abc" "3" "4" # enumeration starts from 1
a<- rep(1:3, times=3)
length(a) <- 2 # shortening
length(a) <- 4 # last two: <NA>
a
a <- 1:5
a ^ 2
a * 2:6
a + 3:7

```
```{r}
# c(1:'abc', 2:'def', 'moe':3) # TODO
1:4 >= 2
```
```{r}
for (i in 1:5){
  print(i) # very slow, avoid `for` whenever possible
}
all(1:6)
any(1:6)
which(1:6 > 4)
```

## Matrices
```{r}
# *, +, -, / element-wise
m1 <- matrix(2:11, nrow=2)
m1 = matrix(3:12, nrow=2)
apply(m1, 1:2, sum)

```
```{r}
m = matrix(1:9, nrow=3)
rownames(m) <- c("my row 1", "my row 2", "my row 3")
```
```{r}
?c # documentation for vector/list
```

## DataFrame
```{r}
df = data.frame(x = 1:4, y = LETTERS[1:4], z = c(T, F)) # data may be of any kind
df
nrow(df)
ncol(df)
names(df)
colnames(df)
df$z
df[[3]]
df[["z"]]
df[df[x] > 0]
# merge(df, df1) # TODO
# read.csv(...) read.table(...) # TODO # same as in Python/Pandas
```
