---
title: "Statistical Tests | Zuev"
output: html_notebook
---
Preparing workspace

```{r echo=FALSE}
df = read.table("E:/Users/vzuev/stu/mat-mod-bio/prac/task1-2020-oct-05/test_data1.txt", header=TRUE)
df
```
1. Let's test `GenBMatur` for normality.
```{r}
shapiro.test(df$GenmBMatur)
```
such a good p-value!

What about `Protein`?
```{r}
shapiro.test(na.omit(df$Protein))
```
No, here we definitely reject the null hypothesis ("data is normally distributed") for $\alpha$-level 0.05 ($p-value > \alpha$).

Dividing data into subgroups by `GrowthType`:
```{r}
df$NonZeroGrowthType <- df$GrowthType > 0
shapiro.test(df[df$NonZeroGrowthType, ] $GenmBMatur)
shapiro.test(df[!df$NonZeroGrowthType, ] $GenmBMatur)

shapiro.test(df[df$NonZeroGrowthType, ] $GenmBMatur)
shapiro.test(df[!df$NonZeroGrowthType, ] $GenmBMatur)

df$NonZeroPolegaemost <- df$Polegaemost > 0
shapiro.test(df[df$NonZeroPolegaemost, ] $Protein)
shapiro.test(df[!df$NonZeroPolegaemost, ] $Protein)

shapiro.test(df[df$NonZeroPolegaemost, ] $Protein)
shapiro.test(df[!df$NonZeroPolegaemost, ] $Protein)
```
Seems that `Protein` does depends neither on `GrowthType` nor on `Polegaemost`.

Performing T-test:
```{r}
my.t_test <- function(x, criterion){
  x1 <- na.omit(x[!criterion])
  x2 <- na.omit(x[criterion])
  denominator = (4 * sqrt(sd(x1)^2/(length(x1)* (length(x1)-1)) + sd(x2)^2/(length(x2)* (length(x2)-1))))
  print("Home-brewed T-test")
  print((mean(x1) - mean(x2)) / denominator)
}
t.test(GenmBMatur ~ NonZeroGrowthType, df)
my.t_test(df$GenmBMatur, df$NonZeroGrowthType)

t.test(GenmBMatur ~ NonZeroPolegaemost, df)
my.t_test(df$GenmBMatur, df$NonZeroPolegaemost)

t.test(Protein ~ NonZeroGrowthType, df)
my.t_test(df$Protein, df$NonZeroGrowthType)

t.test(Protein ~ NonZeroPolegaemost, df)
my.t_test(df$Protein, df$NonZeroPolegaemost)

```

