---
title: "R Notebook"
author: Valerii Zuev
date: 2/15/2022
output: html_notebook
---

```{r}
library(tidyverse)
library(GGally)
```
```{r}
df <- here::here("r/stats2021fall/homework4", "IDZ4_Data_504020121.csv") %>%
  read.csv %>%
  filter(Variant == 4) %>%
  select(!Variant) %>%
  mutate(A = as.factor(A), B = as.factor(B))
head(df) %>% xtable::xtable()
```

```{r}
# ggpairs(df, columns = 1:3, ggplot2::aes(colour = B))

ggplot(data = df, aes(x = Y)) +
  geom_histogram() +
  theme_minimal()
ggplot(data = df, aes(x = Y, fill = B)) +
  geom_histogram() +
  theme_minimal()
ggplot(data = df %>% filter(A == 0), aes(x = Y, fill = A)) +
  geom_histogram() +
  theme_minimal()

```
```{r}
ggplot(data = df %>% filter(A == 1, Visit == 1), aes(x = Y, fill = A)) +
  geom_histogram() +
  theme_minimal()
```
```{r}
lin.models <- list("general" = Y ~ A * B,
                   "additive" = Y ~ A + B,
                   "a_only" = Y ~ A,
                   "b_only" = Y ~ B,
                   "mean" = Y ~ 1) %>% lapply(function(formula) { lm(formula, data = df) })
anova(lin.models$general)
anova(lin.models$additive, lin.models$general) # high p-value (we can reduce the model)
anova(lin.models$additive, lin.models$a_only) # high p-value (we can reduce the model)
anova(lin.models$additive, lin.models$b_only) # small p-value
anova(lin.models$a_only, lin.models$mean) # small p-value

anova(lin.models$general, lin.models$a_only)
```
```{r}
df <- df %>%
  group_by(Visit) %>%
  summarize(MeanY = mean(Y)) %>%
  inner_join(df)
df <- df %>%
  group_by(Visit, A) %>%
  summarize(AMeanY = mean(Y)) %>%
  inner_join(df)
df <- df %>%
  group_by(Visit, B) %>%
  summarize(BMeanY = mean(Y)) %>%
  inner_join(df)
df %>% ggplot(aes(Visit, Y)) +
  geom_point(aes(color = B, size = A)) +
  theme_minimal() +
  geom_line(aes(Visit, MeanY))
df %>% ggplot(aes(Visit, AMeanY, group = A, color = A)) +
  geom_line() +
  theme_minimal()
df %>% ggplot(aes(Visit, BMeanY, group = B, color = B)) +
  geom_line() +
  theme_minimal()
pairs(df)
pairs(df %>% select(Y, ID, A, B))
```
```{r}
# Kolmogorov test
df.t1 <- df[(df$Visit == 2 & df$A == 1),]
df.t2 <- df[(df$Visit == 2 & df$A == 0),]
ks.test(df.t1$Y, df.t2$Y)
```
## ANOVA
```{r, name="ANOVA"}
q <- lm(Y ~ A * B, data = df) # TODO probably not df; what is d16T?
qc <- q$coefficients
x <- c(0, 1) # levels(df$A)
y <- qc[1] + qc[3] * x
# TODO plot
# TODO with
```
Вопрос 3 недоформулирован.
При каждом значении А - тут понятно: по Пирсону (корреляционная матрица, её оцениваем).
По B: предполагаем, что есть некая стационарность. Делаем стратификацию по B и строим вариограмму.
Для вариограммы есть функция, её использовать.

См. методичку в разделе сайта [пособия](https://www.sites.google.com/site/malovsergvas/%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5-%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D1%8B/%D0%B8%D0%B7%D0%B1%D1%80%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D0%B8)

Можете попробовать уже модели