from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_University(object):
    def setupUi(self, University):
        University.setObjectName("University")
        University.resize(975, 694)
        self.centralwidget = QtWidgets.QWidget(University)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.TabWidget.setToolTip("")
        #history - exams
        self.HistExamsTab = QtWidgets.QWidget()
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.HistExamsTab)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.HistExLineEdit = QtWidgets.QLineEdit(self.HistExamsTab)
        self.horizontalLayout.addWidget(self.HistExLineEdit)
        self.HistExPushButton = QtWidgets.QPushButton(self.HistExamsTab)
        self.horizontalLayout.addWidget(self.HistExPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.HistExTableView = QtWidgets.QTableView(self.HistExamsTab)
        self.verticalLayout_2.addWidget(self.HistExTableView)
        self.TabWidget.addTab(self.HistExamsTab, "")
        #history - groups
        self.HistGroupsTab = QtWidgets.QWidget()
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.HistGroupsTab)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.HistGrLineEdit = QtWidgets.QLineEdit(self.HistGroupsTab)
        self.horizontalLayout_2.addWidget(self.HistGrLineEdit)
        self.HistGrPushButton = QtWidgets.QPushButton(self.HistGroupsTab)
        self.horizontalLayout_2.addWidget(self.HistGrPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.HistGrpsTableView = QtWidgets.QTableView(self.HistGroupsTab)
        self.verticalLayout_3.addWidget(self.HistGrpsTableView)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.TabWidget.addTab(self.HistGroupsTab, "")
        #dropped out
        self.DroppedOutTab = QtWidgets.QWidget()
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.DroppedOutTab)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.DrppdComboBox = QtWidgets.QComboBox(self.DroppedOutTab)
        self.DrppdComboBox.addItem("")
        self.DrppdComboBox.addItem("")
        self.DrppdComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.DrppdComboBox)
        self.DrppdLineEdit = QtWidgets.QLineEdit(self.DroppedOutTab)
        self.horizontalLayout_5.addWidget(self.DrppdLineEdit)
        self.DrppdPushButton = QtWidgets.QPushButton(self.DroppedOutTab)
        self.horizontalLayout_5.addWidget(self.DrppdPushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.DrppdTableView = QtWidgets.QTableView(self.DroppedOutTab)
        self.verticalLayout_4.addWidget(self.DrppdTableView)
        self.TabWidget.addTab(self.DroppedOutTab, "")
        #evil teachers
        self.EvilTeachersTab = QtWidgets.QWidget()
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.EvilTeachersTab)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.EvilTComboBox = QtWidgets.QComboBox(self.EvilTeachersTab)
        self.EvilTComboBox.addItem("")
        self.EvilTComboBox.addItem("")
        self.EvilTComboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.EvilTComboBox)
        
        self.EvilTMarkCombo = QtWidgets.QComboBox(self.EvilTeachersTab)
        self.EvilTMarkCombo.addItem("mark: 2")
        self.EvilTMarkCombo.addItem("mark: 3")
        self.EvilTMarkCombo.addItem("mark: 4")
        self.horizontalLayout_7.addWidget(self.EvilTMarkCombo)
        self.EvilTCountLEdit = QtWidgets.QLineEdit(self.EvilTeachersTab)
        self.horizontalLayout_7.addWidget(self.EvilTCountLEdit)
        self.EvilTCountLEdit.setText("type in minimal marks quantity")
        
        self.EvilTLineEdit = QtWidgets.QLineEdit(self.EvilTeachersTab)
        self.horizontalLayout_7.addWidget(self.EvilTLineEdit)
        self.EvilTPushButton = QtWidgets.QPushButton(self.EvilTeachersTab)
        self.horizontalLayout_7.addWidget(self.EvilTPushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.EvilTableView = QtWidgets.QTableView(self.EvilTeachersTab)
        self.verticalLayout_5.addWidget(self.EvilTableView)
        self.TabWidget.addTab(self.EvilTeachersTab, "")
        #make shedule
        self.MkSchedTab = QtWidgets.QWidget()
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.MkSchedTab)
        self.MkSchedTableView = QtWidgets.QTableView(self.MkSchedTab)
        self.verticalLayout_6.addWidget(self.MkSchedTableView)

        self.horizontalLayout6 = QtWidgets.QHBoxLayout()
        self.MkSchedComboBox = QtWidgets.QComboBox(self.MkSchedTab)
        self.MkSchedComboBox.addItem("mode: match teachers with disciplines")
        self.MkSchedComboBox.addItem("mode: define exams")
        self.horizontalLayout6.addWidget(self.MkSchedComboBox)
        self.MkSchedPushButton = QtWidgets.QPushButton(self.MkSchedTab)
        self.horizontalLayout6.addWidget(self.MkSchedPushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout6)
        self.TabWidget.addTab(self.MkSchedTab, "")
        
        #define exams, set marks
        self.DefExmsTab = QtWidgets.QWidget()
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.DefExmsTab)
        self.setMarksTable = QtWidgets.QTableWidget(self.DefExmsTab)
        self.verticalLayout_7.addWidget(self.setMarksTable)
        self.DefExmPushButton = QtWidgets.QPushButton(self.DefExmsTab)
        self.verticalLayout_7.addWidget(self.DefExmPushButton)
        self.TabWidget.addTab(self.DefExmsTab, "")

        #drop students
        self.DropStudentsTab = QtWidgets.QWidget()
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.DropStudentsTab)
        self.DropStTableView = QtWidgets.QTableView(self.DropStudentsTab)
        self.verticalLayout_8.addWidget(self.DropStTableView)
        self.DropStPushButton = QtWidgets.QPushButton(self.DropStudentsTab)
        self.verticalLayout_8.addWidget(self.DropStPushButton)
        self.TabWidget.addTab(self.DropStudentsTab, "")
        self.verticalLayout.addWidget(self.TabWidget)

        #general
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        University.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(University)
        self.statusbar.setObjectName("statusbar")
        University.setStatusBar(self.statusbar)
        self.actionView_shedule = QtWidgets.QAction(University)
        self.actionView_session = QtWidgets.QAction(University)
        self.actionEdit_session = QtWidgets.QAction(University)
        self.actionEdit_shedule = QtWidgets.QAction(University)
        self.actionView_students_flow = QtWidgets.QAction(University)
        self.actionEdit_students_flow = QtWidgets.QAction(University)
        self.actionView_history = QtWidgets.QAction(University)

        self.retranslateUi(University)
        self.TabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(University)

    def retranslateUi(self, University):
        _translate = QtCore.QCoreApplication.translate
        University.setWindowTitle(_translate("University", "University database"))
        self.HistExamsTab.setAccessibleName(_translate("University", "Schedule"))
        self.HistExLineEdit.setText(_translate("University", "type in year"))
        self.HistExPushButton.setText(_translate("University", "Search"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.HistExamsTab), _translate("University", "History - exams"))
        self.HistGrLineEdit.setText(_translate("University", "type in year"))
        self.HistGrPushButton.setText(_translate("University", "Search"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.HistGroupsTab), _translate("University", "History-groups"))
        self.DrppdComboBox.setItemText(0, _translate("University", "1 sem"))
        self.DrppdComboBox.setItemText(1, _translate("University", "2 sem"))
        self.DrppdComboBox.setItemText(2, _translate("University", "both"))
        self.DrppdLineEdit.setText(_translate("University", "type in year"))
        self.DrppdPushButton.setText(_translate("University", "Search"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.DroppedOutTab), _translate("University", "Dropped out"))
        self.EvilTComboBox.setItemText(0, _translate("University", "1 sem"))
        self.EvilTComboBox.setItemText(1, _translate("University", "2 sem"))
        self.EvilTComboBox.setItemText(2, _translate("University", "both"))
        self.EvilTLineEdit.setText(_translate("University", "type in year"))
        self.EvilTPushButton.setText(_translate("University", "Search"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.EvilTeachersTab), _translate("University", "Evil teachers"))
        self.MkSchedPushButton.setText(_translate("University", "Append row"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.MkSchedTab), _translate("University", "Make shedule"))
        self.DefExmPushButton.setText(_translate("University", "Append row"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.DefExmsTab), _translate("University", "Set marks"))
        self.DropStPushButton.setText(_translate("University", "Confirm changes"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.DropStudentsTab), _translate("University", "Drop students"))
        self.textBrowser.setHtml(_translate("University", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Here you will see messages from database</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.actionView_shedule.setText(_translate("University", "View shedule"))
        self.actionView_session.setText(_translate("University", "View session"))
        self.actionEdit_session.setText(_translate("University", "Edit session"))
        self.actionEdit_shedule.setText(_translate("University", "Edit shedule"))
        self.actionView_students_flow.setText(_translate("University", "View students flow"))
        self.actionEdit_students_flow.setText(_translate("University", "Edit students flow"))
        self.actionView_history.setText(_translate("University", "View history"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    University = QtWidgets.QMainWindow()
    ui = Ui_University()
    ui.setupUi(University)
    University.show()
    sys.exit(app.exec_())

